<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DriverTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('driver')->insert([
            [
               'idDriver' => 1,
                'name' => 'Verstappen',
                'firstName' => 'Max',
                'lastName' => 'Verstappen',
                'number' => 1,
                'birth' => '1997-09-30',
                'country' => 'Netherlands',
                'placeBirth' => 'Hasselt, Belgium',
                'podiums' => 100,
                'grandprix' => 188,
                'bibliography' => NULL,
                'imgDriver' => 'MaxVerstappen.png',
                'imgDriverProfile' => 'MaxVerstappen_profile.png',
                'imgNumber' => 'MaxVerstappen_num.png',
                'imgCountry' => 'Netherlands.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 1,
            ],
            [
                'idDriver' => 2,
                'name' => 'Perez',
                'firstName' => 'Sergio',
                'lastName' => 'Perez',
                'number' => 11,
                'birth' => '1990-01-26',
                'country' => 'Mexico',
                'placeBirth' => 'Guadalajara, Mexico',
                'podiums' => 37,
                'grandprix' => 261,
                'bibliography' => NULL,
                'imgDriver' => 'SergioPerez.png',
                'imgDriverProfile' => 'SergioPerez_profile.png',
                'imgNumber' => 'SergioPerez_num.png',
                'imgCountry' => 'Mexico.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 1,
            ],
            [
                'idDriver' => 3,
                'name' => 'Leclerc',
                'firstName' => 'Charles',
                'lastName' => 'Leclerc',
                'number' => 16,
                'birth' => '1997-10-16',
                'country' => 'Monaco',
                'placeBirth' => 'Monte Carlo, Monaco',
                'podiums' => 31,
                'grandprix' => 128,
                'bibliography' => NULL,
                'imgDriver' => 'CharlesLeclerc.png',
                'imgDriverProfile' => 'CharlesLeclerc_profile.png',
                'imgNumber' => 'CharlesLeclerc_num.png',
                'imgCountry' => 'Monaco.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 2,
            ],
            [
                'idDriver' => 4,
                'name' => 'Russell',
                'firstName' => 'George',
                'lastName' => 'Russell',
                'number' => 63,
                'birth' => '1998-02-15',
                'country' => 'United Kingdom',
                'placeBirth' => 'King\'s Lynn, England',
                'podiums' => 11,
                'grandprix' => 107,
                'bibliography' => NULL,
                'imgDriver' => 'GeorgeRussell.png',
                'imgDriverProfile' => 'GeorgeRussell_profile.png',
                'imgNumber' => 'GeorgeRussell_num.png',
                'imgCountry' => 'GreatBritain.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 4,
            ],
            [
                'idDriver' => 5,
                'name' => 'Piastri',
                'firstName' => 'Oscar',
                'lastName' => 'Piastri',
                'number' => 81,
                'birth' => '2001-04-06',
                'country' => 'Australia',
                'placeBirth' => 'Melbourne, Victoria',
                'podiums' => 2,
                'grandprix' => 25,
                'bibliography' => NULL,
                'imgDriver' => 'OscarPiastri.png',
                'imgDriverProfile' => 'OscarPiastri_profile.png',
                'imgNumber' => 'OscarPiastri_num.png',
                'imgCountry' => 'Australia.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 3,
            ],
            [
                'idDriver' => 6,
                'name' => 'Sainz',
                'firstName' => 'Carlos',
                'lastName' => 'Sainz',
                'number' => 55,
                'birth' => '1994-09-01',
                'country' => 'Spain',
                'placeBirth' => 'Madrid, Spain',
                'podiums' => 19,
                'grandprix' => 187,
                'bibliography' => NULL,
                'imgDriver' => 'CarlosSainz.png',
                'imgDriverProfile' => 'CarlosSainz_profile.png',
                'imgNumber' => 'CarlosSainz_num.png',
                'imgCountry' => 'Spain.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 2,
            ],
            [
                'idDriver' => 7,
                'name' => 'Alonso',
                'firstName' => 'Fernando',
                'lastName' => 'Alonso',
                'number' => 14,
                'birth' => '1981-07-29',
                'country' => 'Spain',
                'placeBirth' => 'Oviedo, Spain',
                'podiums' => 106,
                'grandprix' => 383,
                'bibliography' => NULL,
                'imgDriver' => 'FernandoAlonso.png',
                'imgDriverProfile' => 'FernandoAlonso_profile.png',
                'imgNumber' => 'FernandoAlonso_num.png',
                'imgCountry' => 'Spain.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 5,
            ],
            [
                'idDriver' => 8,
                'name' => 'Norris',
                'firstName' => 'Lando',
                'lastName' => 'Norris',
                'number' => 4,
                'birth' => '1999-11-13',
                'country' => 'United Kingdom',
                'placeBirth' => 'Bristol, England',
                'podiums' => 13,
                'grandprix' => 107,
                'bibliography' => NULL,
                'imgDriver' => 'LandoNorris.png',
                'imgDriverProfile' => 'LandoNorris_profile.png',
                'imgNumber' => 'LandoNorris_num.png',
                'imgCountry' => 'GreatBritain.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 3,
            ],
            [
                'idDriver' => 9,
                'name' => 'Hamilton',
                'firstName' => 'Lewis',
                'lastName' => 'Hamilton',
                'number' => 44,
                'birth' => '1985-01-07',
                'country' => 'United Kingdom',
                'placeBirth' => 'Stevenage, England',
                'podiums' => 197,
                'grandprix' => 335,
                'bibliography' => NULL,
                'imgDriver' => 'LewisHamilton.png',
                'imgDriverProfile' => 'LewisHamilton_profile.png',
                'imgNumber' => 'LewisHamilton_num.png',
                'imgCountry' => 'GreatBritain.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 4,
            ],
            [
                'idDriver' => 10,
                'name' => 'Bearman',
                'firstName' => 'Oliver',
                'lastName' => 'Bearman',
                'number' => 38,
                'birth' => NULL,
                'country' => 'United Kingdom',
                'placeBirth' => NULL,
                'podiums' => NULL,
                'grandprix' => NULL,
                'bibliography' => NULL,
                'imgDriver' => 'OliverBearman.png',
                'imgDriverProfile' => 'OliverBearman_profile.png',
                'imgNumber' => 'OliverBerman_num.png',
                'imgCountry' => 'GreatBritain.jpg',
                'mainDriver' => 0,
                'Team_idTeam' => 2,
            ],
            [
                'idDriver' => 11,
                'name' => 'Hulkenberg',
                'firstName' => 'Nico',
                'lastName' => 'Hulkenberg',
                'number' => 27,
                'birth' => '1987-08-19',
                'country' => 'Germany',
                'placeBirth' => 'Emmerich am Rhein, Germany',
                'podiums' => 0,
                'grandprix' => 209,
                'bibliography' => NULL,
                'imgDriver' => 'NicoHulkenberg.png',
                'imgDriverProfile' => 'NicoHulkenberg_profile.png',
                'imgNumber' => 'NicoHulkenberg_num.png',
                'imgCountry' => 'Germany.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 6,
            ],
            [
                'idDriver' => 12,
                'name' => 'Stroll',
                'firstName' => 'Lance',
                'lastName' => 'Stroll',
                'number' => 18,
                'birth' => '1998-10-29',
                'country' => 'Canada',
                'placeBirth' => 'Montreal, Canada',
                'podiums' => 3,
                'grandprix' => 146,
                'bibliography' => NULL,
                'imgDriver' => 'LanceStroll.png',
                'imgDriverProfile' => 'LanceStroll_profile.png',
                'imgNumber' => 'LanceStroll_num.png',
                'imgCountry' => 'Canada.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 5,
            ],
            [
                'idDriver' => 13,
                'name' => 'Albon',
                'firstName' => 'Alexander',
                'lastName' => 'Albon',
                'number' => 23,
                'birth' => '1996-03-23',
                'country' => 'Thailand',
                'placeBirth' => 'London, England',
                'podiums' => 2,
                'grandprix' => 84,
                'bibliography' => NULL,
                'imgDriver' => 'AlexanderAlbon.png',
                'imgDriverProfile' => 'AlexanderAlbon_profile.png',
                'imgNumber' => 'AlexanderAlbon_num.png',
                'imgCountry' => 'Thailand.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 7,
            ],
            [
                'idDriver' => 14,
                'name' => 'Zhou',
                'firstName' => 'Zhou',
                'lastName' => 'Guanyu',
                'number' => 24,
                'birth' => '1999-05-30',
                'country' => 'China',
                'placeBirth' => 'Shanghai, China',
                'podiums' => 0,
                'grandprix' => 47,
                'bibliography' => NULL,
                'imgDriver' => 'ZhouGuanyu.png',
                'imgDriverProfile' => 'ZhouGuanyu_profile.png',
                'imgNumber' => 'ZhouGuanyu_num.png',
                'imgCountry' => 'China.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 8,
            ],
            [
                'idDriver' => 15,
                'name' => 'Magnussen',
                'firstName' => 'Kevin',
                'lastName' => 'Magnussen',
                'number' => 20,
                'birth' => '1992-10-05',
                'country' => 'Denmark',
                'placeBirth' => 'Roskilde, Denmark',
                'podiums' => 1,
                'grandprix' => 167,
                'bibliography' => NULL,
                'imgDriver' => 'KevinMagnussen.png',
                'imgDriverProfile' => 'KevinMagnussen_profile.png',
                'imgNumber' => 'KevinMagnussen_num.png',
                'imgCountry' => 'Denmark.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 6,
            ],
            [
                'idDriver' => 16,
                'name' => 'Ricciardo',
                'firstName' => 'Daniel',
                'lastName' => 'Ricciardo',
                'number' => 3,
                'birth' => '1989-07-01',
                'country' => 'Australia',
                'placeBirth' => 'Perth, Australia',
                'podiums' => 32,
                'grandprix' => 242,
                'bibliography' => NULL,
                'imgDriver' => 'DanielRicciardo.png',
                'imgDriverProfile' => 'DanielRicciardo_profile.png',
                'imgNumber' => 'DanielRicciardo_num.png',
                'imgCountry' => 'Australia.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 9,
            ],
            [
                'idDriver' => 17,
                'name' => 'Ocon',
                'firstName' => 'Esteban',
                'lastName' => 'Ocon',
                'number' => 31,
                'birth' => '1996-09-17',
                'country' => 'France',
                'placeBirth' => 'Évreux, Normandy',
                'podiums' => 3,
                'grandprix' => 136,
                'bibliography' => NULL,
                'imgDriver' => 'EstebanOcon.png',
                'imgDriverProfile' => 'EstebanOcon_profile.png',
                'imgNumber' => 'EstebanOcon_num.png',
                'imgCountry' => 'France.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 10, 
            ],
            [
                'idDriver' => 18,
                'name' => 'Tsunoda',
                'firstName' => 'Yuki',
                'lastName' => 'Tsunoda',
                'number' => 22,
                'birth' => '2000-05-11',
                'country' => 'Japan',
                'placeBirth' => 'Sagamihara, Japan',
                'podiums' => 0,
                'grandprix' => 69,
                'bibliography' => NULL,
                'imgDriver' => 'YukiTsunoda.png',
                'imgDriverProfile' => 'YukiTsunoda_profile.png',
                'imgNumber' => 'YukiTsunoda_num.png',
                'imgCountry' => 'Japan.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 9,
            ],
            [
                'idDriver' => 19,
                'name' => 'Sargeant',
                'firstName' => 'Logan',
                'lastName' => 'Sargeant',
                'number' => 2,
                'birth' => '2000-12-31',
                'country' => 'United States',
                'placeBirth' => 'Fort Lauderdale, Florida',
                'podiums' => 0,
                'grandprix' => 24,
                'bibliography' => NULL,
                'imgDriver' => 'LoganSargent.png',
                'imgDriverProfile' => 'LoganSargent_profile.png',
                'imgNumber' => 'LoganSargent_num.png',
                'imgCountry' => 'UnitedStates.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 7,
            ],
            [
                'idDriver' => 20,
                'name' => 'Bottas',
                'firstName' => 'Valtteri',
                'lastName' => 'Bottas',
                'number' => 77,
                'birth' => '1989-08-28',
                'country' => 'Finland',
                'placeBirth' => 'Nastola, Finland',
                'podiums' => 67,
                'grandprix' => 225,
                'bibliography' => NULL,
                'imgDriver' => 'ValtteriBottas.png',
                'imgDriverProfile' => 'ValtteriBottas_profile.png',
                'imgNumber' => 'ValtteriBottas_num.png',
                'imgCountry' => 'Finland.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 8,
            ],
            [
                'idDriver' => 21,
                'name' => 'Gasly',
                'firstName' => 'Pierre',
                'lastName' => 'Gasly',
                'number' => 10,
                'birth' => '1996-02-07',
                'country' => 'France',
                'placeBirth' => 'Rouen, France',
                'podiums' => 4,
                'grandprix' => 133,
                'bibliography' => NULL,
                'imgDriver' => 'PierreGasly.png',
                'imgDriverProfile' => 'PierreGasly_profile.png',
                'imgNumber' => 'PierreGasly_num.png',
                'imgCountry' => 'France.jpg',
                'mainDriver' => 1,
                'Team_idTeam' => 10,
            ],
            [
                'idDriver' => 22,
                'name' => 'De Vries',
                'firstName' => 'Nyck',
                'lastName' => 'De Vries',
                'number' => 45,
                'birth' => '1995-04-06',
                'country' => 'Netherlands',
                'placeBirth' => NULL,
                'podiums' => NULL,
                'grandprix' => NULL,
                'bibliography' => NULL,
                'imgDriver' => NULL,
                'imgDriverProfile' => NULL,
                'imgNumber' => NULL,
                'imgCountry' => NULL,
                'mainDriver' => 0,
                'Team_idTeam' => NULL,
            ],
            [
                'idDriver' => 23,
                'name' => 'Lawson',
                'firstName' => 'Liam',
                'lastName' => 'Lawson',
                'number' => 40,
                'birth' => NULL,
                'country' => 'New Zealander',
                'placeBirth' => NULL,
                'podiums' => NULL,
                'grandprix' => NULL,
                'bibliography' => NULL,
                'imgDriver' => NULL,
                'imgDriverProfile' => NULL,
                'imgNumber' => NULL,
                'imgCountry' => NULL,
                'mainDriver' => 0,
                'Team_idTeam' => NULL,
                ]
            
            ]);
    
        }
    }
    
