<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PrixTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prix')->insert([
            [
                'idPrix' => 1,
                'name' => 'Jeddah Corniche Circuit',
                'grandPrixName' => 'STC Saudi Arabian Grand Prix',
                'comunName' => 'Jeddah',
                'country' => 'Saudi Arabia',
                'firstGrandPrix' => 2021,
                'distance' => 308.45,
                'length' => 6.174,
                'laps' => 50,
                'info' => '<h2>When was the track built?</h2><p>The Jeddah Corniche Circuit is, you won’t be surprised to hear, a temporary street circuit (albeit adorned with some permanent sections), located on the Corniche – a 30km coastal resort area of the ancient Saudi Arabian city of Jeddah. Designed by the Tilke company, in conjunction with Formula 1’s own Motorsports team – who used Google Earth for their initial investigations into potential layouts – F1’s Ross Brawn said of the track: “What we want to see is a race circuit. We don’t want Mickey Mouse circuits. We don’t want those old classic street circuits with 90 degree turns. We want fast sweeping circuits, circuits which are going to challenge the drivers – and they are going to love it.”</p><h2>When was its first Grand Prix?</h2><p>The inaugural Saudi Arabian Grand Prix took place in 2021, the race joining its Middle Eastern counterparts in Bahrain and Abu Dhabi – while like those races, the Saudi Arabian Grand Prix also takes place under floodlights.</p><h2>What\’s the circuit like?</h2><p>Fast. Very fast. Average speeds around the Jeddah Corniche Circuit are around 250km/h – quicker than those at Silverstone, and second on the 2021 calendar only to Monza – aka ‘The Temple of Speed’. It is, quite simply, the fastest street circuit ever seen in Formula 1 – while the track also features the most corners on the calendar with 27, many of them quick, sinuous bends as the drivers wend their way along the Jeddah waterfront.</p><h2>Why go?</h2><p>The Saudi Arabian Grand Prix promises a sun-soaked festival of Formula 1, located on an idyllic stretch of the Kingdom’s coastline. The on-track action is stunning, as the drivers get to grips with this rapid street track, while Jeddah itself comes alive as the city revels in hosting the F1 circus.</p><h2>Where is the best place to watch?</h2><p>The average speeds around the Jeddah Corniche Circuit are such that any grandstand provides a spectacular viewing location. Nonetheless, the gladiatorial splendour of the grandstand surrounding the banked Turn 13 corner makes for a very special spot for F1 fans.</p>',
                'imgCircuts' => 'JeddahCornicheCircuit.png',
                'imgBanner' => 'JeddahCornicheCircuit_banner.jpg',
                'imgAbout' => 'JeddahCornicheCircuit_about.png',
            ],
            [
                'idPrix' => 2,
                'name' => 'Bahrain International Circuit',
                'grandPrixName' => 'Gulf Air Bahrain Grand Prix',
                'comunName' => 'Sakhir',
                'country' => 'Bahrain',
                'firstGrandPrix' => 2004,
                'distance' => 308.238,
                'length' => 5.412,
                'laps' => 57,
                'info' => '<h2>When was the track built?</h2><p>Ground was broken for the Bahrain International Circuit in December 2002. Like the Yas Marina Circuit in Abu Dhabi, the developers had a blank, sandy canvas to work with, and with that fashioned the technical, 5.4km track designed by Hermann Tilke.</p><h2>When was its first Grand Prix?</h2><p>It was 2004 when the drivers first lined up under an unusually cloudy sky for the inaugural Bahrain Grand Prix. The race was dominated (like many in 2004) by the two Ferraris, with Michael Schumacher winning out from Rubens Barrichello, while the crowds were also treated to a fantastic dog-fight between the Jaguar of Mark Webber and the Renault of Fernando Alonso.</p><h2>What’s the circuit like?</h2><p>You can usually expect great racing and decent amounts of overtaking in Bahrain, while the drivers have to contend with wind, racing under floodlights and the difficulty of finding a decent set-up with the wide temperature fluctuations between sessions. The track’s most challenging point is the tight, downhill, off-camber Turn 10 left-hander, while the fast run through Turn 12 is another highlight, allowing the racers to really feel their cars coming alive.</p><h2>Why go?</h2><p>Given the nature of the track, race-goers in Bahrain have always got a decent chance of being treated to a \’duel in the desert\’ or three. Away from the race track, Bahrain, as you might expect, is a great place to catch some rays, with the 33-island archipelago kingdom featuring some jaw-dropping resorts. And if you want to do some racing yourself, the Bahrain International Karting Circuit, located right next to the track, is one of the world’s top karting facilities.</p><h2>Where is the best place to watch?</h2><p>Your options are slightly limited in Bahrain, given that the organisers understandably don’t want loads of fans having to traipse out into the middle of a hot desert to watch the action! We reckon your best bet is to get a place in the Batelco grandstand, giving you a great view of cars charging into Turn 8, hammering through 9 and 10 and then passing you on the run down to the short-apex Turn 11. Otherwise, the grandstand on the outside of Turns 1 and 2 will allow you to watch overtaking aplenty on either track layout.</p>',
                'imgCircuts' => 'BahrainInternationalCircuit.png',
                'imgBanner' => 'BahrainInternationalCircuit_banner.jpg',
                'imgAbout' => 'BahrainInternationalCircuit_about.png',
            ],
            [
                'idPrix' => 3,
                'name' => 'Albert Park Circuit',
                'grandPrixName' => 'Rolex Australian Grand Prix',
                'comunName' => 'Melbourne',
                'country' => 'Australia',
                'firstGrandPrix' => 1996,
                'distance' => 306.124,
                'length' => 5.278,
                'laps' => 58,
                'info' => '<h2>When was the track built?</h2><p>The deal to host Formula 1 in Melbourne was done in 1993, with the decision taken to create a circuit using a mixture of the existing roads around the city’s Albert Park – mainly Aughtie Drive and Lakeside Drive if you fancy driving it yourself – with a little detour through the Lakeside Stadium’s car park.</p><h2>When was its first Grand Prix?</h2><p>Just four months after Adelaide held its last Australian Grand Prix at the end of 1995, the Formula 1 teams were back in Australia for Melbourne\’s first Grand Prix at the start of 1996. That race is most often remembered for Martin Brundle’s infamous Jordan crash at Turn 3 after he launched himself off the back of Johnny Herbert’s Sauber.</p><h2>What’s the circuit like?</h2><p>As a temporary facility, Albert Park can be quite bumpy, while the circuit at the start of the weekend is often slippery, rubbering in as the sessions progress. It’s also a circuit that requires a well-sorted chassis, with several spots on the track where the drivers require a reactive front end to allow them to chuck it into a corner. Melbourne is also one of the faster tracks on the calendar, with Max Verstappen’s 2023 pole lap set at an average of over 250km/h.</p><h2>Why go?</h2><p>Often found on lists of the world’s best cities, Melbourne is a blast all year round – and it only gets better when Formula 1 rolls into town. There are bars and restaurants aplenty, you’re right by the beach, while the race’s appearance at the start of Australia’s autumn means the temperatures should be peachy.</p><h2>Where is the best place to watch?</h2><p>If you want to get in a grandstand, opt for either the Waite stand overlooking Turn 10, or the Brabham Grandstand on the outside of Turn 2 to watch cars jostling for position through the first chicane. Alternatively, there are some nice general admission spots on the far side of the lake – go for either between Turns 8-9 or 9-10 if you fancy some F1 picnic feels.</p>',
                'imgCircuts' => 'AlbertParkCircuit.png',
                'imgBanner' => 'AlbertParkCircuit_banner.jpg',
                'imgAbout' => 'AlbertParkCircuit_about.png',
            ],
            [
                'idPrix' => 4,
                'name' => 'Suzuka International Racing Course',
                'grandPrixName' => 'MSC Cruises Japanese Grand Prix',
                'comunName' => 'Suzuka',
                'country' => 'Japan',
                'firstGrandPrix' => 1987,
                'distance' => 307.471,
                'length' => 5.807,
                'laps' => 53,
                'info' => '<h2>When was the track built?</h2><p>In 1962. Soichiro Honda, whose car company you may have heard of, was a man with big ambitions. Seeking to turn Honda into an automotive powerhouse, he decided his company should have its own test track. Dutchman John Hugenholtz got the nod, and drew up the now-iconic ‘crossover’ Suzuka track – although original drawings saw the track pass over and under itself a full three times, which would have been sweet!</p><h2>When was its first Grand Prix?</h2><p>Despite most people agreeing that Suzuka is a worthy successor to sliced bread in the ‘Best Thing’ stakes, the Japanese track was a relative latecomer to the F1 calendar, making its first appearance in 1987. Nigel Mansell would remember that weekend well, after he suffered a crash in qualifying that ruled him out of the race, gifting that year’s championship to his bitter rival Nelson Piquet.</p><h2>What’s the circuit like?</h2><p>Show us a racing a driver who doesn’t love Suzuka, and we’ll show you a liar. The high-speed track remains one of the ultimate driving challenges, with the snaking ‘S’ Curves, the two commitment-rewarding Degners and the white-knuckle ride of 130R all highlights in a series of highlights at what is one of F1’s seminal tracks. And hey, it’s got a crossover, which is always cool, right?</p><h2>Why go?</h2><p>A track that has witnessed an unfair share of legendary F1 moments (not least between Messrs Prost and Senna), a unique set of fans with an unabashed commitment to playing Formula 1 dress-up, a Ferris wheel, and great food. Okay, for most of us it’s a long slog to get there, but surely a better question is: ‘Why not go?’</p><h2>Where is the best place to watch?</h2><p>Take your pick. Grandstands D and E overlook the ‘S’ Curves, giving you an amazing chance to watch downforce and commitment working in perfect harmony as the drivers negotiate the sinuous turns. Elsewhere, the left flank of Grandstand G places you at the inside of 130R, which should be a bit of a treat, while if it’s overtaking you want, Grandstand I will give you a view of the incident-attracting Hairpin.</p>',
                'imgCircuts' => 'SuzukaInternationalRacingCourse.png',
                'imgBanner' => 'SuzukaInternationalRacingCourse_banner.jpg',
                'imgAbout' => 'SuzukaInternationalRacingCourse_about.png',
            ],
            [
                'idPrix' => 5,
                'name' => 'Shanghai International Circuit',
                'grandPrixName' => 'Lenovo Chinese Grand Prix',
                'comunName' => 'Shanghai',
                'country' => 'China',
                'firstGrandPrix' => 2004,
                'distance' => 305.066,
                'length' => 5.451,
                'laps' => 56,
                'info' => '<h2>When was the track built?</h2><p>In April 2003, a marshland in the Jiading District of Shanghai was earmarked for Formula 1 greatness. Eighteen months and around $450 million later, the state-of-the-art Shanghai International Circuit was complete.</p><h2>When was its first Grand Prix?</h2><p>The 2004 season featured two new races, one of which was the Chinese Grand Prix (the other was Bahrain). If either were added to try and stop Ferrari from winning everything, however, it didn’t work – Michael Schumacher won in Bahrain, while Rubens Barrichello triumphed in China.</p><h2>What’s the circuit like?</h2><p>The circuit’s pleasing form when seen from the air – it’s designed to look like the Chinese symbol for ‘shang’, meaning upwards – is equally pleasing to the drivers on terra firma. There’s a unique start to the lap as the drivers fly into the ever-tightening Turns 1 and 2, before they dart left through 3 and 4. The super-high g force Turns 7 and 8 are loved by the drivers, while the circuit also features one of the longest straights on the calendar, the 1.2km stretch that separates Turns 13-14.</p><h2>Why go?</h2><p>Shanghai has expanded itself into one of the world’s most dynamic and lively cities since the start of the millennium, making it an awesome F1 tourist stop. The sprawling Pudong district is chock full of hip bars and amazing restaurants. Then when it’s time to go racing, just hop on the Shanghai Metro’s Line 11 and get off at the Shanghai Circuit stop 60 minutes later.</p><h2>Where is the best place to watch?</h2><p>We’re going to recommend Grandstand K, overlooking the Turn 14-15 hairpin, where you’ll be in the best seats to watch all the overtaking. Alternatively, head for Turn 6, the track’s other best passing spot, where Daniel Ricciardo sealed his 2018 win with a brave move on Valtteri Bottas.</p>',
                'imgCircuts' => 'ShanghaiInternationalCircuit.png',
                'imgBanner' => 'ShanghaiInternationalCircuit_banner.jpg',
                'imgAbout' => 'ShanghaiInternationalCircuit_about.png',
            ],
            [
                'idPrix' => 6,
                'name' => 'Miami International Autodrome',
                'grandPrixName' => 'crypto.com Miami Grand Prix',
                'comunName' => 'Miami Gardens',
                'country' => 'United States',
                'firstGrandPrix' => 2022,
                'distance' => 308.326,
                'length' => 5.412,
                'laps' => 57,
                'info' => '<h2>When was the track built?</h2><p>Having made its F1 debut in May 2022, the Miami International Autodrome is a temporary circuit, but one designed to have a permanent feel. Set in the Hard Rock Stadium complex in Miami Gardens, home to the NFL’s famous Miami Dolphins franchise, the track is the culmination of a development process that simulated no less than 36 different layouts before settling on a thrilling, 19-turn lap that provides a street circuit vibe, not dissimilar to Melbourne’s Albert Park.</p><h2>When was its first Grand Prix?</h2><p>The inaugural Miami Grand Prix took place in 2022, the Florida race joining its Texan counterpart in Austin to become the second US race on the calendar – and the 11th different American venue to host a round of the Formula 1 world championship.</p><h2>What\’s the circuit like?</h2><p>A street-track spectacular. With the Hard Rock Stadium at its epicentre, the 5.41km layout features 19 corners, three straights, three DRS zones, and top speeds of over 340km/h. There are elevation changes too, the main one found between Turns 13 and 16, with the track heading over an exit ramp and under various flyovers across uneven ground. The Turn 14-15 chicane, meanwhile, has an uphill approach, with a crest in the middle, and then drops down on exit.</p><h2>Why go?</h2><p>The Hard Rock Stadium knows how to put on a show – it has hosted six Super Bowls, two Baseball World Series and numerous rock concerts. Put it at the heart of a track designed to encourage close racing while meeting the highest safety standards and you have a sure-fire winner for spectators. Then there’s Miami itself – famed for its sandy beaches, art deco vibe, vibrant multiculturalism and rich sporting heritage, it’s an essential destination for those visiting the Sunshine State.</p><h2>Where is the best place to watch?</h2><p>When viewing a sporting event in a purpose-built stadium, it’s hard to go wrong. In fact, you could walk around the top deck of the Hard Rock Stadium and see every corner of the track – pretty unique. As for the best passing spots, a seat near Turns 1, 11 or 17 should put you in the thick of the action.</p>',
                'imgCircuts' => 'MiamiInternationalAutodrome.png',
                'imgBanner' => 'MiamiInternationalAutodrome_banner.jpg',
                'imgAbout' => 'MiamiInternationalAutodrome_about.png',
            ],
            [
                'idPrix' => 7,
                'name' => 'Autodromo Enzo e Dino Ferrari',
                'grandPrixName' => 'MSC Cruises Gran Premio Del Made In Italy e Dell’Emilia-Romagna Grand Prix',
                'comunName' => 'Imola',
                'country' => 'Italy',
                'firstGrandPrix' => 1980,
                'distance' => 309.049,
                'length' => 4.909,
                'laps' => 63,
                'info' => '<h2>When was the track built?</h2><p>Imola – or the Autodromo Internazionale Enzo e Dino Ferrari as it’s been known since 1988 – had its foundation stone laid in March 1950. It was ready for testing by October 1952, while racing began at the circuit in 1953.</p><h2>When was its first Grand Prix?</h2><p>Imola first hosted a non-championship F1 race in 1963, but it would take some politicking with Monza in 1980 before the track was awarded the honour of hosting the Italian Grand Prix for the first time that year. From 1981, the two tracks worked together in perfect harmony, with Imola taking on its famous ‘San Marino’ title, and going on to host a total of 27 Grands Prix up until 2006. It returned as venue for the Emilia Romagna Grand Prix in 2020.</p><h2>What’s the circuit like?</h2><p>A thrill ride. After testing his AlphaTauri AT01 at the track in the build-up to the 2020 season, Pierre Gasly called the experience one of the best he’d ever had in a Formula 1 car, while his then-team mate Daniil Kvyat remarked that “an F1 car through corners like Acque Minerali – the entrance is so fast, it’s so cool. It really gives you a lot of adrenaline.” The anti-clockwise circuit is certainly fast, with an old-school feel as the drivers put it on the line in iconic corners like the aforementioned Acque Minerali and Piratella.</p><h2>Why go?</h2><p>Like neighbouring Mugello, Imola is nestled in a fantastic part of the world, with the Tuscan hills to the south, the Adriatic beaches to the east and the gastronomic delights of cities like Bologna, Parma and Modena to the west – as well as the F1 mecca that is Ferrari’s HQ in nearby Maranello. There’s also no getting around the fact that a visit to Imola is an opportunity for F1 fans to pay their respects to Ayrton Senna and Roland Ratzenberger, who lost their lives at the 1994 San Marino Grand Prix.</p><h2>Where is the best place to watch?</h2><p>The stand on the outside of Acque Minerali is a great spot to see an F1 machine being pushed to its absolute limits, as the drivers struggle to get the cars down to speed for the tight right-hander before blasting back up the hill to the Variante Alta chicane.</p>',
                'imgCircuts' => 'AutodromoEnzoeDinoFerrari.png',
                'imgBanner' => 'AutodromoEnzoeDinoFerrari_banner.jpg',
                'imgAbout' => 'AutodromoEnzoeDinoFerrari_about.png',
            ],
            [
                'idPrix' => 8,
                'name' => 'Circuit de Monaco',
                'grandPrixName' => 'Grand Prix de Monaco',
                'comunName' => 'Monaco',
                'country' => 'Monaco',
                'firstGrandPrix' => 1950,
                'distance' => 260.286,
                'length' => 3.37,
                'laps' => 78,
                'info' => '<h2>When was the track built?</h2><p>In 1215, sort of – that’s when Monaco was first established as a colony of Genoa.</p><h2>When was its first Grand Prix?</h2><p>It was 1929 when racing engines first reverberated around the Principality, after cigarette manufacturer Antony Noghes decided to organise a race with his pals from the Automobile Club de Monaco. The race was part of the calendar in the first year of the Formula 1 World Championship in 1950, and hasn’t been off it since 1955.</p><h2>What’s the circuit like?</h2><p>Incredibly narrow and totally iconic. Nelson Piquet memorably described driving around Monaco as “like riding a bicycle around your living room”… which is fair. Despite that, it’s a challenge that nearly all drivers love, forcing them to put their skills on the line and rewarding millimetric accuracy. Overtaking on the tight streets is harder, however, with the 2003 Grand Prix witnessing a grand total of zero passing moves!</p><h2>Why go?</h2><p>A holiday on the French Riviera, plus the chance to watch Formula 1 cars pounding past places where Monegasques usually go to buy a pint of milk? It really is as fun as it sounds. On top of that, the chance to walk the track after a day’s hard lapping – or even enjoy your dinner on it at one of the terrasse bars – is not to be missed.</p><h2>Where is the best place to watch?</h2><p>Assuming you can’t get into one of the overhanging apartment blocks around the circuit (or onto a boat) shoot for anything from Grandstands L to P, which are clustered around the Swimming Pool section of the track, and where drivers hurl their cars through the tight chicane at 200km/h. Or, for a more spectacular vista, try Grandstand B, overlooking the ritzy Casino Square.</p>',
                'imgCircuts' => 'CircuitdeMonaco.png',
                'imgBanner' => 'CircuitdeMonaco_banner.jpg',
                'imgAbout' => 'CircuitdeMonaco_about.png',
            ],
            [
                'idPrix' => 9,
                'name' => 'Circuit Gilles-Villeneuve',
                'grandPrixName' => 'AWS Grand Prix Du Canada',
                'comunName' => 'Montréal',
                'country' => 'Canada',
                'firstGrandPrix' => 1978,
                'distance' => 305.27,
                'length' => 4.361,
                'laps' => 70,
                'info' => '<h2>When was the track built?</h2><p>The man-made Notre Dame Island in the middle of the St Lawrence River was created for the 1967 Expo 67 World\’s Fair. Once the expo and the ensuing 1976 Montreal Summer Olympics had left town, some clever people decided to make a race track out of the island’s roads. And lo, the Circuit Ile Notre-Dame, as it then was, came to be.</p><h2>When was its first Grand Prix?</h2><p>With the Canadian Grand Prix having been in search of a permanent home for a number of years in the 1960s and 1970s, the Circuit Ile Notre-Dame first hosted the race in 1978. Fittingly, Gilles Villeneuve claimed his maiden win, at the track that would end up bearing his name.</p><h2>What’s the circuit like?</h2><p>The fast, low-downforce circuit is one of the drivers’ favourites. The track is quite stop-start, with lots of heavy-braking chicanes and the famous hairpin to get the anchors working hard. Out of the corners, though, the track is quick and flowing, while the most iconic piece of the circuit comes right at the end of the lap: the Wall of Champions, so-called after excursions into it from Damon Hill, Jacques Villeneuve and Michael Schumacher during the 1999 Canadian Grand Prix weekend.</p><h2>Why go?</h2><p>The Montrealais really embrace their Grand Prix weekend, with the charming city turning into an F1-loving party town in the week leading up to the race. For the Grand Prix itself, the leafy setting makes the Circuit Gilles-Villeneuve one of Formula 1’s most laidback venues.</p><h2>Where is the best place to watch?</h2><p>It’s got to be one of either Grandstand 15, 21 or 24, the three that surround the hairpin. It makes for a real amphitheatre vibe down there, as well as allowing you to see all the hairpin overtakes.</p>',
                'imgCircuts' => 'CircuitGilles-Villeneuve.png',
                'imgBanner' => 'CircuitGilles-Villeneuve_banner.jpg',
                'imgAbout' => 'CircuitGilles-Villeneuve_about.png',
            ],
            [
                'idPrix' => 10,
                'name' => 'Circuit de Barcelona-Catalunya',
                'grandPrixName' => 'Aramco Gran Premio de España',
                'comunName' => 'Barcelona',
                'country' => 'Spain',
                'firstGrandPrix' => 1991,
                'distance' => 307.236,
                'length' => 4.657,
                'laps' => 66,
                'info' => '<h2>When was the track built?</h2><p>The Circuit de Barcelona-Catalunya was built as part of the 1992 Barcelona Olympics development programme. The foundation stone was laid in 1989, while the first car race was a round of the 1991 Spanish Touring Car Championship.</p><h2>When was its first Grand Prix?</h2><p>Two weeks after the touring cars raced at Barcelona, it was Formula 1’s turn. The track enjoyed a sensational debut, with Nigel Mansell and Ayrton Senna’s famous eyeball-to-eyeball drag race down the straight, before Mansell took the lead and drove on to victory.</p><h2>What’s the circuit like?</h2><p>The drivers love the Circuit de Barcelona-Catalunya, which is just as well, as they have traditionally spent huge amounts of time pounding around it during winter testing. The track is a good mix of high- and low-speed corners, with the challenging Turn 3 right-hander a great chance to evaluate the balance of the car your team’s designers have given you to fight with for the season.</p><h2>Why go?</h2><p>You don’t need us to tell you that Barcelona is one of the world’s great cities, even if we just sort of did. Food, culture, beaches – it’s all there, making a Spanish Grand Prix holiday a properly attractive proposition.</p><h2>Where is the best place to watch?</h2><p>You’ve got plenty of choice, with almost the whole track overlooked by grandstands or general admission areas. On the outside of Turn 1, Grandstand A will let you see the best overtaking spot on the track, while the general admission area around Turn 3 will provide the awe-inspiring sight of Formula 1 cars being pushed to the limit of their downforce capabilities.</p>',
                'imgCircuts' => 'CircuitdeBarcelona-Catalunya.png',
                'imgBanner' => 'CircuitdeBarcelona-Catalunya_banner.jpg',
                'imgAbout' => 'CircuitdeBarcelona-Catalunya_about.png',
            ],
            [
                'idPrix' => 11,
                'name' => 'Red Bull Ring',
                'grandPrixName' => 'Qatar Airways Austrian Grand Prix',
                'comunName' => 'Spielberg',
                'country' => 'Austria',
                'firstGrandPrix' => 1970,
                'distance' => 306.452,
                'length' => 4.318,
                'laps' => 71,
                'info' => '<h2>When was the track built?</h2><p>The fearsome, original Osterreichring was originated in 1969 as a replacement for the Zeltweg airfield circuit. The track known today as the Red Bull Ring was more or less created over the winter of 1995-6, when Hermann Tilke was engaged to turn the Osterreichring into a shorter, more modern race track.</p><h2>When was its first Grand Prix?</h2><p>The A1-Ring, as it was then called, was opened in 1996, with Formula 1 arriving at the circuit a year later. Jacques Villeneuve won the race, while Jean Alesi had a spectacular crash when his Benetton climbed up the Ferrari of Eddie Irvine. Alesi’s team mate Gerhard Berger, meanwhile, used his home Grand Prix to announce his F1 retirement.</p><h2>What’s the circuit like?</h2><p>It’s only wee, bless it, but the Red Bull Ring packs a lot into a short lap. The first half rewards power, as the cars blast along three straights separated by a pair of uphill right-handers. But then as the drivers work their way downhill, the circuit becomes a regular toboggan ride, as the cars canyon through a series of quick corners, including the exhilarating Rindt right-hander, named for Austria’s first F1 champion.</p><h2>Why go?</h2><p>Race tracks don’t come much more picturesque than the Red Bull Ring, set in an idyllic natural bowl in the Styrian mountains. That makes for a pleasant environment for a Grand Prix, while if you’re after tourist attractions to visit after the race, look no further than the museum in Graz dedicated to the city’s favourite son: Arnold Schwarzenegger.</p><h2>Where is the best place to watch?</h2><p>One of Formula 1’s best views is to be had at the Red Bull Ring’s ‘Nord’ grandstand, based around the outside of what used to be the Bosch Kurve at the Osterreichring. Here, you’ll have a great vantage point across much of the track as it drops away from you down the natural slope of the circuit.</p>',
                'imgCircuts' => 'RedBullRing.png',
                'imgBanner' => 'RedBullRing_banner.jpg',
                'imgAbout' => 'RedBullRing_about.png',
            ],
            [
                'idPrix' => 12,
                'name' => 'Silverstone Circuit',
                'grandPrixName' => 'Qatar Airways British Grand Prix',
                'comunName' => 'Silverstone',
                'country' => 'Great Britain',
                'firstGrandPrix' => 1950,
                'distance' => 306.198,
                'length' => 5.891,
                'laps' => 52,
                'info' => '<h2>When was the track built?</h2><p>Little did those laying the perimeter road to the RAF Silverstone airfield in 1942 know that they were setting down what would become one of the world’s greatest race tracks. But, well, they were! The Silverstone circuit was first used for a proper motor race in 1947 – although sadly, a local sheep lost its life during the proceedings…</p><h2>When was its first Grand Prix?</h2><p>Silverstone was the first Grand Prix, hosting the inaugural Formula 1 World Championship round on May 13 1950. Old campaigner Giuseppe Farina, who’d take that year’s title, won the race in his Alfa Romeo 158.</p><h2>What’s the circuit like?</h2><p>At the 2018 British Grand Prix, Lewis Hamilton compared a flat-out lap around Silverstone to flying a fighter jet, which should tell you all you need to know about the Northamptonshire circuit. Despite numerous layout changes over the years, Silverstone has always maintained its essential character as one of the fastest tracks on the F1 calendar, while historic corners like Maggotts, Becketts and Abbey provide some of the biggest challenges for racing drivers anywhere in the world.</p><h2>Why go?</h2><p>It’s hard to stop the goose bumps from prickling as you walk around one of the great cathedrals of motorsport, while in terms of atmosphere, the British fans are always reliably raucous – this is the country that invented football (that’s soccer, mind), after all..</p><h2>Where is the best place to watch?</h2><p>The Becketts grandstand has to rank highly on the ultimate list of places to watch an F1 car in action – believe us, your eyes will be on stalks when you see how quickly the drivers zip through Maggotts and Becketts. Further along the track, the Stowe grandstands will place you at one of the best overtaking spots, while watching the drivers chuck their cars into that corner on their own is nearly as good</p>',
                'imgCircuts' => 'SilverstoneCircuit.png',
                'imgBanner' => 'SilverstoneCircuit_banner.jpg',
                'imgAbout' => 'SilverstoneCircuit_about.png',
            ],
            [
                'idPrix' => 13,
                'name' => 'Hungaroring',
                'grandPrixName' => 'Hungarian Grand Prix',
                'comunName' => 'Budapest',
                'country' => 'Hungary',
                'firstGrandPrix' => 1986,
                'distance' => 306.63,
                'length' => 4.381,
                'laps' => 70,
                'info' => '<h2>When was the track built?</h2><p>Work began on the Hungaroring in 1985, and the track was race-ready just nine months later. The Hungarian government had originally considered reviving the old Nepliget park circuit in Budapest in a bid to host Formula 1 in the country, but in the end decided to create a purpose-built facility instead.</p><h2>When was its first Grand Prix?</h2><p>The year was 1986. Nelson Piquet won the first F1 race around the Hungaroring, famously slithering his Williams around the outside of Ayrton Senna’s Lotus to take the lead.</p><h2>What’s the circuit like?</h2><p>The lack of straights at the Hungaroring often sees it compared to a karting circuit – and it’s true, the resemblance is uncanny. With several series of corners to string together, teams opt for Monaco levels of downforce, with a well-sorted chassis tending to be rewarded over horsepower given the short straights on offer. It’s a challenge many of the drivers relish, however, with finding a good rhythm key to setting fast lap times.</p><h2>Why go?</h2><p>Hungary in July is usually hot hot hot. The good news if you’re at the track, though, is that there’s a water park close by – the Mogyorodi Aquarena vizi szorakoztatopark – which should be a good place to cool off. Away from aqueous activities, the circuit is only 20km from Budapest, putting you close to one of Europe’s most fascinating, storied and lively city centres.</p><h2>Where is the best place to watch?</h2><p>The track is built in a natural bowl, a bit like the UK\’s Brands Hatch. That means that any of the grandstands located on or around the main straight should provide a view of other parts of the track too, giving you more F1 bang for your, er, forint.</p>',
                'imgCircuts' => 'Hungaroring.png',
                'imgBanner' => 'Hungaroring_banner.jpg',
                'imgAbout' => 'Hungaroring_about.png',
            ],
            [
                'idPrix' => 14,
                'name' => 'Circuit de Spa-Francorchamps',
                'grandPrixName' => 'Rolex Belgian Grand Prix',
                'comunName' => 'Spa-Francorchamps',
                'country' => 'Belgium',
                'firstGrandPrix' => 1950,
                'distance' => 308.052,
                'length' => 7.004,
                'laps' => 44,
                'info' => '<h2>When was the track built?</h2><p>The original, triangle-shaped track was built in 1921, with designers Jules de Thier and Henri Langlois van Ophem using public roads between the towns of Francorchamps, Malmedy, and Stavelot to create an amazing 14.9km circuit taking in the forests and rolling hills of the beautiful Ardennes region. The track was redeveloped in 1979, and although the new circuit is only half the original\’s length, it’s still the longest on the current calendar at 7.004km.</p><h2>When was its first Grand Prix?</h2><p>Having hosted a non-championship Grand Prix as long ago as 1924, Belgium’s iconic circuit was one of just seven to be part of Formula 1’s maiden championship in 1950. That race was won by the legendary Juan Manuel Fangio, who led home an Alfa Romeo one-two ahead of team mate Nino Farina.</p><h2>What’s the circuit like?</h2><p>Spa is among Formula 1 drivers’ most loved tracks, with its mix of long straights and challenging fast corners allowing them to push their cars to the edge of their capabilities – if it’s dry, that is. The size of the track and the nature of Belgian weather means it can sometimes be raining on one part of the track and dry on another, meaning grip can vary from one corner to the next. Keep an eye on the thrilling Eau Rouge, arguably the most famous sequence of corners in the world, as the drivers flick left, right and then up the hill through Raidillon.</p><h2>Why go?</h2><p>What’s not to love about one of Europe’s classic tracks? Only the truly great drivers conquer Spa, with Ayrton Senna and Michael Schumacher among those to master this magical circuit. Add in the wonderful setting of the Ardennes forest and it’s no surprise that it’s a fan favourite, with a record 265,000 spectators turning out to watch the 2017 Spa showdown.</p><h2>Where is the best place to watch?</h2><p>The elevated grandstand located near Eau Rouge gives you the best view of the iconic corner, while also boasting panoramic views from La Source through to Raidillon. But if you fancy taking in some of the best trackside atmosphere, then the grandstand located on the Pouhon corner should be right up your street.</p>',
                'imgCircuts' => 'CircuitdeSpa-Francorchamps.png',
                'imgBanner' => 'CircuitdeSpa-Francorchamps_banner.jpg',
                'imgAbout' => 'CircuitdeSpa-Francorchamps_about.png',
            ],
            [
                'idPrix' => 15,
                'name' => 'Circuit Zandvoort',
                'grandPrixName' => 'Heineken Duth Grand Prix',
                'comunName' => 'Zandvoort',
                'country' => 'Netherlands',
                'firstGrandPrix' => 1952,
                'distance' => 306.587,
                'length' => 4.259,
                'laps' => 72,
                'info' => '<h2>When was the track built?</h2><p>Like Silverstone, Zandvoort was first opened in 1948, part of the wave of post-war motorsport enthusiasm that swept across Europe. Originally made up of a mixture of permanent track and public roads that snaked through the sand dunes of the Zandvoort resort town, the Dutch Automobile Racing Club – who initiated the plans for the circuit – brought in 1927 Le Mans winner Sammy Davis to consult on the layout for the original 4.2km track.</p><h2>When was its first Grand Prix?</h2><p>Formula 1 arrived in the Dutch dunes in 1952, with Alberto Ascari dominating the race as he led home a 1-2-3 for Ferrari. Formula 1 would go on to race on and off at the track until 1985 – before, in 2019, the announcement came that the championship would return to Zandvoort for 2020, after a 35-year hiatus. The Covid-19 pandemic meant that became 36 years and a 2021 date.</p><h2>What’s the circuit like?</h2><p>‘Really quick’, ‘pretty insane’, ‘crazy’ and ‘old-school’ were words used by the current crop of F1 drivers when asked to describe the Zandvoort track that many of them tackled in their junior category days. We’d also add ‘undulating’ to that list. The Zandvoort track swoops and flows through the sand dunes, creating a rollercoaster-like feel to the lap. And while the circuit was modernised in time for F1’s most recent return – including increasing the banking angle at the famous Tarzan corner to an Indianapolis Motor Speedway-trumping 18 degrees – Zandvoort remains a proper, challenging drivers’ track.</p><h2>Why go?</h2><p>Zandvoort combines a lot of enticing features for an F1 fan. There’s the historic track, which famously featured in John Frankenheimer’s Grand Prix, and was the scene of many great F1 moments over the years (Gilles Villeneuve’s three-wheeled lap, anyone?). There’s the atmosphere, which with Max Verstappen on the grid is always guaranteed to be electric, and most definitely orange-hued. And then there’s the beachside location, just a 30-minute train ride outside of Amsterdam. What’s not to love?</p><h2>Where is the best place to watch?</h2><p>We recommend taking to either the first turn at Tarzan, or to one of the banked corners, either at Arie Luyendijkbocht – the final turn on the track – or Hugenholtzbocht. For F1’s 2021 return, the latter corner was both widened and banked into a parabolic corner, to allow cars to run side by side, and at the same speed, through it. Exciting is an understatement…</p>',
                'imgCircuts' => 'CircuitZandvoort.png',
                'imgBanner' => 'CircuitZandvoort_banner.jpg',
                'imgAbout' => 'CircuitZandvoort_about.png',
            ],
            [
                'idPrix' => 16,
                'name' => 'Autodromo Nazionale Monza',
                'grandPrixName' => 'Pierlli Gran Premio D\’Italia',
                'comunName' => 'Monza',
                'country' => 'Italy',
                'firstGrandPrix' => 1950,
                'distance' => 306.72,
                'length' => 5.793,
                'laps' => 53,
                'info' => '<h2>When was the track built?</h2><p>Constructed in just 110 days in 1922, the Autodromo Nazionale Monza was the world’s third purpose-built race track, coming after Brooklands in the UK and Indianapolis in the US. Like those two tracks, the original circuit featured a daunting series of banked curves, as well as much of the ‘outfield’ section that’s still in use today.</p><h2>When was its first Grand Prix?</h2><p>Monza opened its doors on September 3 1922, just a week before it hosted that year’s Italian Grand Prix. It was then part of the original Formula 1 calendar in 1950, and has held the Italian Grand Prix every year bar one since.</p><h2>What’s the circuit like?</h2><p>Rapido! Formula 1’s fastest ever lap was set at Monza – Williams driver Juan Pablo Montoya’s 260.6km/h effort during practice for the 2004 Grand Prix – which should give you some idea of the nature of the track the locals call ‘La Pista Magica’. Cars are on full throttle for 80% of the lap, and hit their Vmax on the circuit’s 1.1km start/finish straight. From there, they roar off into the historic park section, where a series of big stops into tight chicanes give the brakes a good workout.</p><h2>Why go?</h2><p>The parkland setting of Monza, located just to the north east of Italy’s fashion capital Milan, makes for a relaxed, leafy setting for a Grand Prix, while the preserved Monza banking – spot it in the background as the cars exit the Parabolica, as well as on the flyover bridge they pass under en route to the Variante Ascari – leaves you in no doubt that you’re in the presence of a very special race track.</p><h2>Where is the best place to watch?</h2><p>Aim for the grandstand at the Variante del Rettifilo to witness the awesome spectacle of cars braking from around 350km/h to just 70km/h before negotiating the tight chicane. This is also one of the track’s best overtaking spots, as well as a magnet for first-lap tussles.</p>',
                'imgCircuts' => 'AutodromoNazionaleMonza.png',
                'imgBanner' => 'AutodromoNazionaleMonza_banner.jpg',
                'imgAbout' => 'AutodromoNazionaleMonza_about.png',
            ],
            [
                'idPrix' => 17,
                'name' => 'Baku City Circuit',
                'grandPrixName' => 'Qatar Airways Azerbaijan Grand Prix',
                'comunName' => 'Baku',
                'country' => 'Azerbaijan',
                'firstGrandPrix' => 2016,
                'distance' => 306.049,
                'length' => 6.003,
                'laps' => 51,
                'info' => '<h2>When was the track built?</h2><p>It wasn’t – Baku is the newest street circuit on the Formula 1 calendar, joining the ranks of Monaco, Melbourne and Singapore.</p><h2>When was its first Grand Prix?</h2><p>The first Grand Prix in Baku was held in 2016, as the European Grand Prix. That was followed by the inaugural Azerbaijan Grand Prix in 2017, which witnessed one of the biggest upsets of the season, with Daniel Ricciardo winning out from Valtteri Bottas and the Williams of Lance Stroll, while Lewis Hamilton and Sebastian Vettel engaged in some argy-bargy behind the Safety Car.</p><h2>What’s the circuit like?</h2><p>A mixture of wide and open and tight and twisty. The lonnnnng main straight along the Baku shoreline is a slipstreaming mecca, and with cars able to run three abreast into Turn 1, the action often looks more IndyCar than F1. However from there, the track loops around into the city’s narrow, winding Icheri Sheher old town, dramatically wending past Baku’s medieval city walls. As in Monaco, slightest mistakes are punished quickly and severely, while set-up wise, the teams are forced to choose between downforce for the twisty bits and less drag for the straight.</p><h2>Why go?</h2><p>As with all city tracks, spectating at the Azerbaijan Grand Prix means that you’re right in the middle of the action when the cars get put back in their boxes. Baku itself is a buzzing city, while food is a key part of Azerbaijan’s culture, incorporating elements of Turkish and Middle Eastern cuisine – so eat up!</p><h2>Where is the best place to watch?</h2><p>The principal Absheron grandstand at the end of the main straight should be high up on your viewing wish-list, as you’ll be watching the cars braking from around 350km/h into the 90-degree Turn 1 – and you’ll likely get to watch the lion’s share of overtaking too. Elsewhere, the Icheri Sheher grandstand provides a unique vantage point, as you watch the cars wriggle through the city gate section and power on down to the super-fast Turn 13-15 complex.</p>',
                'imgCircuts' => 'BakuCityCircuit.png',
                'imgBanner' => 'BakuCityCircuit_banner.jpg',
                'imgAbout' => 'BakuCityCircuit_about.png',
            ],
            [
                'idPrix' => 18,
                'name' => 'Marina Bay Street Circuit',
                'grandPrixName' => 'Singapore Airlines Singapore Grand Prix',
                'comunName' => 'Singapore',
                'country' => 'Singapore',
                'firstGrandPrix' => 2008,
                'distance' => 306.143,
                'length' => 4.94,
                'laps' => 62,
                'info' => '<h2>When was the track built?</h2><p>The Marina Bay Circuit arrived on the scene in 2008. A street track with the city\’s famous skyline as its spectacular backdrop, the initial circuit plan by Herman Tilke was refined by KBR Inc, while the event has quickly established itself as one of the standouts on the F1 calendar.</p><h2>When was its first Grand Prix?</h2><p>In 2008, Singapore had the honour of hosting the first night-time race in F1 history. The Grand Prix – the 15th round of that season – proved a huge hit with the teams and drivers, while Renault’s Fernando Alonso claimed a controversial victory.</p><h2>What’s the circuit like?</h2><p>The Marina Bay Circuit is one of the most physically demanding on the calendar, its bumpy street surface coupled with humid conditions giving the drivers plenty to think about. Even after a 2023 layout change reducing the number of corners from 23 to 19, they are working the wheel a lot, too, around the high-speed lap – the physical stress causing them to lose as much as 3kg in body weight over the course of a race.</p><h2>Why go?</h2><p>If you want to see Singapore at its best, there’s no better time to do so than when Formula 1 arrives in the heart of this buzzing city. Get the lay of the land by taking a ride on the Singapore Flyer, a giant Ferris wheel overlooking the track’s permanent pits complex, then get stuck into Singapore’s incredible bar and restaurant scene. Cocktail fanatics should also make a pilgrimage to the famous Raffles Hotel – the proper home of the Singapore Sling (non-alcoholic versions are available!)</p><h2>Where is the best place to watch?</h2><p>Get yourself comfy in the grandstand located at Turn 1, which offers spectacular views as the cars accelerate into the first corner, before braking hard and whipping through Turns 2 and 3. You’ll get a great view of the start too – expect to see plenty of sparks fly as the drivers blast off the line.</p>',
                'imgCircuts' => 'MarinaBayStreetCircuit.png',
                'imgBanner' => 'MarinaBayStreetCircuit_banner.jpg',
                'imgAbout' => 'MarinaBayStreetCircuit_about.png',
            ],
            [
                'idPrix' => 19,
                'name' => 'Circuit of The Americas',
                'grandPrixName' => 'Pirelli United States Grand Prix',
                'comunName' => 'Austin',
                'country' => 'United States',
                'firstGrandPrix' => 2012,
                'distance' => 308.405,
                'length' => 5.513,
                'laps' => 56,
                'info' => '<h2>When was the track built?</h2><p>The Circuit of The Americas, designed by Hermann Tilke in collaboration with American architectural firm HKS, endured something of a nervy start, with construction suffering several setbacks. It was well worth the wait, though, when 1978 F1 champion Mario andretti opened the track on October 21 2012.</p><h2>When was its first Grand Prix?</h2><p>F1 first raced at the Circuit of The Americas in 2012, for the first United States Grand Prix since the 2007 race at Indianapolis. Unsurprisingly, over 100,000 spectators packed out the Austin venue, witnessing Lewis Hamilton’s last ever win in a McLaren before his switch to Mercedes for 2013.</p><h2>What’s the circuit like?</h2><p>If the corners at COTA seem familiar, they should be. Turns 3 through 6 look not dissimilar to Silverstone\’s high-speed run through Maggotts/Becketts or the S Curves at Suzuka, while Turns 12 through 15 mimic Hockenheim\’s stadium section. Meanwhile, the uphill run into wide, wide Turn 1 – hey, everything’s bigger in Texas, right? – has provided some fine overtaking action in the track’s short life.</p><h2>Why go?</h2><p>There’s a reason Austin is often regarded as America’s coolest city, with great food and a vibrant nightlife, all united under the banner of the city’s unofficial slogan: ‘Keep Austin Weird’. Then when racing starts, you’ll be in attendance at one of the great modern race tracks. With the Americans’ attitude to partying, you won’t want to miss out!</p><h2>Where is the best place to watch?</h2><p>You’re spoilt for choice. If you sit in the main grandstand on the start-finish straight you’ll get – in true US style – the benefit of an in-seat food and drinks service, while those in the stand at Turn 1 enjoy a view all the way to downtown Austin. But if you want to see the racing action up close, find a way into the the Stadium Section stands at Turns 15/16.</p>',
                'imgCircuts' => 'CircuitofTheAmericas.png',
                'imgBanner' => 'CircuitofTheAmericas_banner.jpg',
                'imgAbout' => 'CircuitofTheAmericas_about.png',
            ],
            [
                'idPrix' => 20,
                'name' => 'Autódromo Hermanos Rodríguez',
                'grandPrixName' => 'Gran Premio De La Ciudad De México',
                'comunName' => 'Mexico City',
                'country' => 'Mexico',
                'firstGrandPrix' => 1963,
                'distance' => 305.354,
                'length' => 4.304,
                'laps' => 71,
                'info' => '<h2>When was the track built?</h2><p>In 1959. The father of Mexico’s most famous racing brothers, Ricardo and Pedro Rodriguez, was an advisor to Mexican President Adolfo Lopez Mateo, and had a word in his boss’s ear about building a racing circuit in Mexico City’s Magdalena Mixiuhca sports park using the existing internal roads. El Presidente liked the idea, and work on the track was completed in under a year.</p><h2>When was its first Grand Prix?</h2><p>Formula 1 cars arrived in 1962 for a non-championship race, returning the following year for a proper, bona fide Grand Prix. That 1963 race was won by Jim Clark, while for the next few years, Mexico’s fiesta vibes meant it became the traditional season-ender for Formula 1. Mexico was welcomed back onto the F1 calendar in 2015.</p><h2>What’s the circuit like?</h2><p>High up! The Autodromo Hermanos Rodriguez sits over 2km above sea level, making the 4.3km lap a breathless experience. The track still largely follows the outline of the original 1959 circuit, the main difference being that the spectacular – and spectacularly scary – Peralta corner is now bisected, with the circuit instead winding through the old Foro Sol baseball stadium, providing one F1’s most unique vistas.</p><h2>Why go?</h2><p>Mexico City is one of the world’s most buzzing, vibrant metropolises. And with the Autodromo Hermanos Rodriguez located just to the east of the city, with a metro station ready to whip you into the downtown at the end of each day’s racing action, the Mexican Grand Prix is a fantastic chance to properly mix sport and culture.</p><h2>Where is the best place to watch?</h2><p>Fight tooth and nail for a spot in the Foro Sol. Not only will you get to peer down into the cockpits of the drivers as they pass through the stadium, but the atmosphere when the podium ceremony unfolds there has to be experienced to be believed.</p>',
                'imgCircuts' => 'AutódromoHermanosRodríguez.png',
                'imgBanner' => 'AutódromoHermanosRodríguez_banner.jpg',
                'imgAbout' => 'AutódromoHermanosRodríguez_about.png',
            ],
            [
                'idPrix' => 21,
                'name' => 'Autódromo José Carlos Pace',
                'grandPrixName' => 'Lenovo Grande Prêmio De São Paulo',
                'comunName' => 'São Paulo',
                'country' => 'Brazil',
                'firstGrandPrix' => 1973,
                'distance' => 305.879,
                'length' => 4.309,
                'laps' => 71,
                'info' => '<h2>When was the track built?</h2><p>Building work began on what ended up being called the Autodromo Jose Carlos Pace – but what is more commonly referred to as Interlagos – all the way back in 1938. The track designers took their inspiration from three main circuits: Brooklands in the UK, Roosevelt Raceway in the USA and Montlhery in France.</p><h2>When was its first Grand Prix?</h2><p>Buoyed by the success of Brazil’s Emerson Fittipaldi, Formula 1 first jetted into Interlagos for a world championship race in 1973. Fans were treated to a home win in the first three Brazilian Grands Prix, with Fittipaldi victorious in 1973 and 1974, while Carlos Pace won in 1975.</p><h2>What’s the circuit like?</h2><p>Like many pre-World War II tracks, Interlagos features banked corners, with the drivers beginning their lap on a sort of half oval – in fact, between 1957 and the track’s return to the F1 calendar in 1990, Interlagos could be run as a giant oval. After wiggling through the Senna S and down to Turn 4, the drivers then go through a snaking in-field section with some challenging camber changes, before slinging back up the hill and through the banked final turn.</p><h2>Why go?</h2><p>A carnival atmosphere really does dominate in Brazil, and watching Formula 1 cars alongside the locals is something every F1 fan should experience. True, it doesn’t look like there’ll be a local driver to cheer on any time soon, but that won’t stop the party at Interlagos.</p><h2>Where is the best place to watch?</h2><p>Because of the bowl-like nature of the track, a place in Grandstand A on the banked entry to the start-finish straight will give you a double whammy of views, allowing you to see the cars winding through the infield section and then passing underneath you. On the other end of the straight, Grandstand M will put you on top of the first corner and the Senna S, the best spot to watch overtakes on the track.</p>',
                'imgCircuts' => 'AutódromoJoséCarlosPace.png',
                'imgBanner' => 'AutódromoJoséCarlosPace_banner.jpg',
                'imgAbout' => 'AutódromoJoséCarlosPace_about.png',
            ],
            [
                'idPrix' => 22,
                'name' => 'Las Vegas Strip Circuit',
                'grandPrixName' => 'Heineken Silver Las Vegas Grand Prix',
                'comunName' => 'Las Vegas',
                'country' => 'United States',
                'firstGrandPrix' => 2023,
                'distance' => 309.958,
                'length' => 6.201,
                'laps' => 50,
                'info' => '<h2>When was the track built?</h2><p>The 2023 Formula 1 season saw drivers tackle an all-new circuit in Las Vegas, encompassing the very best the City of Lights has to offer – including the famous Strip.</p><h2>When was its first Grand Prix?</h2><p>Las Vegas previously staged two F1 races – under the Caesars Palace Grand Prix moniker – in 1981 and 1982. It played host to the season finale on both occasions, with Williams driver Alan Jones winning the 1981 race and Michele Alboreto taking his maiden F1 victory for Tyrrell at the 1982 encounter. Meanwhile, Nelson Piquet and Keke Rosberg clinched the title in ’81 and ’82 respectively with fifth-place finishes.</p><h2>What’s the circuit like?</h2><p>Located in the heart of Las Vegas, the new 6.2km, 17-turn street circuit winds its way past iconic locations like Caesars Palace, the Bellagio and the Venetian. With average speeds similar to Monza, otherwise known as F1’s ‘Temple of Speed’, fans are guaranteed plenty of action and overtaking.</p><h2>Why go?</h2><p>There continues to be a huge buzz around the Las Vegas Grand Prix, fuelled by 2023\’s spectacular inaugural event that gave drivers and fans a taste for more. With the party atmosphere the resort city is famous for, a Saturday night race under the lights and entertainment off track to match the action on it, this is one of the events to attend on the Formula 1 calendar.</p><h2>Where is the best place to watch?</h2><p>A host of ticketing options are available for the Las Vegas weekend, ranging from VIP packages to grandstand seating and general admission. But whatever you go for, a spectacular experience awaits – as cars blast around a high-speed circuit set against one of the most vibrant backdrops F1 has ever seen.</p>',
                'imgCircuts' => 'LasVegasStripCircuit.png',
                'imgBanner' => 'LasVegasStripCircuit_banner.jpg',
                'imgAbout' => 'LasVegasStripCircuit_about.png',
            ],
            [
                'idPrix' => 23,
                'name' => 'Lusail International Circuit',
                'grandPrixName' => 'Qatar Airways Qatar Grand Prix',
                'comunName' => 'Qatar',
                'country' => 'Qatar',
                'firstGrandPrix' => 2021,
                'distance' => 308.611,
                'length' => 4.419,
                'laps' => 57,
                'info' => '<h2>When was the track built?</h2><p>The Lusail International Circuit, located on the outskirts of the capital city of Doha, was built in preparation for hosting Qatar’s first ever MotoGP event in 2004, with the circuit completed in just over a year.</p><h2>When was its first Grand Prix?</h2><p>2021 represented the first time Qatar had ever hosted the FIA Formula One World Championship – with the country signing an additional 10-year deal to host the sport from 2023.</p><h2>What’s the circuit like?</h2><p>Designed primarily with motorcycle racing in mind, the 5.4-kilometre Lusail International Circuit is a fast and flowing track, where medium- and high-speed corners predominate. Over one kilometre of the track’s total length is made up of the main straight, which provides plenty of overtaking opportunities into Turn 1.</p><h2>Why go?</h2><p>If you live in the northern hemisphere and the thought of escaping colder climes in October appeals, you’ll be well catered for in Qatar, with average temperatures around 28 degrees Celsius at that time of year. Unsurprisingly with that kind of weather, Qatar is a great country for outdoor pursuits, be that karting at Lusail itself, or trips into the desert to go sandboarding, camel riding and 4x4ing.</p><h2>Where is the best place to watch?</h2><p>The Main Grandstand puts you at the heart of the action, with panoramic views of the start-finish straight, the pit lane and the team garages. Meanwhile, the T2 Grandstand offers outstanding vantage points to enjoy the action through the circuit’s opening corners.</p>',
                'imgCircuts' => 'LusailInternationalCircuit.png',
                'imgBanner' => 'LusailInternationalCircuit_banner.jpg',
                'imgAbout' => 'LusailInternationalCircuit_about.png',
            ],
            [
                'idPrix' => 24,
                'name' => 'Yas Marina Circuit',
                'grandPrixName' => 'Etihad Airways Abu Dhabi Grand Prix',
                'comunName' => 'Yas Island',
                'country' => 'Abu Dhabi',
                'firstGrandPrix' => 2009,
                'distance' => 306.183,
                'length' => 5.281,
                'laps' => 58,
                'info' => '<h2>When was the track built?</h2><p>In 2006, plans were announced to develop Yas Island, located just to the east of Abu Dhabi, into a new tourist destination, with a major part of the plans centring around a 5.5km race track. The diggers rolled into what would become the Yas Marina Circuit in May 2007, with the project completed by October 2009.</p><h2>When was its first Grand Prix?</h2><p>In 2009. The track debuted as that year’s Formula 1 season finale, with Red Bull’s Sebastian Vettel winning from team mate Mark Webber and the already-crowned 2009 champion Jenson Button. Vettel would go on to secure his first title in Abu Dhabi a year later, amid much crying.</p><h2>What’s the circuit like?</h2><p>The Hermann Tilke-designed track is dominated by its 1.2km straight between Turns 5 and 6 – which, with slow-speed corners marking its beginning and end, makes it a honeypot for overtaking moves. Other highlights include the tricky run through Turns 10 and 11 into 12, which forces the drivers to brake hard with bags of lateral load still on the car. Track modifications ahead of the 2021 race, shortening the lap slightly to 5.28km, have only added to its excitement.</p><h2>Why go?</h2><p>Yas Island was a blank canvas for developers to turn into a tourist attraction, and 11 years and $40 billion later, they’ve nearly finished doing just that. Seven hotels, Ferrari’s indoor theme park, a mall, a water park, a golf course, a beach, a concert arena and a nightclub, all framed by perfect Emirati weather. What more could you want?</p><h2>Where is the best place to watch?</h2><p>Assuming you can’t get a room with a trackside view in the spectacular whale-shaped Yas Hotel – or a berth in a boat’s cabin in the marina – opt for a spot in the West Grandstand, a great place to watch all the overtaking action into Turn 6. Or if you’re more there for the atmos, stick yourself in the Main Grandstand overlooking the start-finish straight and enjoy Abu Dhabi’s famed pyrotechnics. It might be worth trying to get a seat high up in whatever grandstand you choose, though, if you’re looking to keep out of the sun.</p>',
                'imgCircuts' => 'YasMarinaCircuit.png',
                'imgBanner' => 'YasMarinaCircuit_banner.jpg',
                'imgAbout' => 'YasMarinaCircuit_about.png',
            ]
        ]);
    }
}
